### ISSUE TITLE
Decide whether sendPeer is necessary

### ISSUE THREAD

**Issue by jorndorff** [pingryiRT/ChatClient#10]
The peer class has a sendPeer method. Is it necessary? Mitchell's comment indicates it may not be. If we can simplify we should (we're already at 300 lines).

**Comment by jorndorff** [comment]
Looks like this is removed from the Manual version now right? Can someone confirm and close this issue if that code is gone?

**Comment by mpavlak2018** [comment]
It's gone, just forgot to close the issue...
