### ISSUE TITLE
Debugging output is vague

### ISSUE THREAD

**Issue by jorndorff** [pingryiRT/ChatClient#13]
Should we update the 'a' 'r' 'c' output to be more clear?

I'm not sure what those are confirming.

In the future we should consider making that output optional entirely so it doesn't appear in a production environment.

**Comment by mpavlak2018** [comment]
Right now it is (or should be) commented out from the exhibit, we might want to leave it just in case we decide to use it again if we make changes/decide to use the (better) target -- (they were leftover from the start of this, just confirming that the threads did reach/go to their respective functions--so acceptor receiver connector etc) we might just want to delete them and close... if we need them in the future we can always write them again -- Thoughts?

**Comment by jorndorff** [comment]
I have no problem keeping them in, I just wanted more detail. I've updated the strings (but still left the code commented) in 0869df8b3d471be18d829022790f35d94102de22
