### ISSUE TITLE
Remove SingleClient and replace it with SingleClientManual

### ISSUE THREAD

**Issue by mpavlak2018** [pingryiRT/ChatClient#15]

**Comment by jorndorff** [comment]
I've manually merged the changes from 34b1fd75eb1bdf806e5c600999e7dacacb9ce387 into  `SingleClientManual.py` in 5346fe02b3cd1a5f2dff40a0b89e727ea85cf3b6. I believe it is now safe to remove `SingleClient.py`.

In the future, let's be better about using branches so we don't have to manually merge.
