### ISSUE TITLE
Split the Single Client manual into separate files and import them as needed

### ISSUE THREAD

**Issue by mpavlak2018** [pingryiRT/ChatClient#16]

**Comment by jorndorff** [comment]
I think the idea here is to split the project into three files for better abstraction.
1. `peer.py` just contains the Peer class
2. `Network.py` just contains the Network class (currently known as threadFunctions)
3. `main.py` or another name contains the main program.

**Comment by mpavlak2018** [comment]
I split it into Peer.py, Main.py, ThreadFunctions.py, and ThreadExtension.py (we should probably take a look at renaming those to see if we want to make it better -- ThreadFunctions right now is just the network stuff, and ThreadExtension extends (not sure about the correct word in python) threading.Thread and defines our __init__ and run functions -- I'll close this and make a new issue about the names
