### ISSUE TITLE
Remove commented and no-longer-needed code.

### ISSUE THREAD

**Issue by mpavlak2018** [pingryiRT/ChatClient#17]

**Comment by jorndorff** [comment]
I've changed the issue name to better reflect what needs to be removed. The part about splitting out files is already covered in issue #16 . And I've opened a separate issue about locks in #18 .

This issue can be resolved when the commented code (init and old version of printThis) is removed.

**Comment by mpavlak2018** [comment]
Question, do we want to remove them yet? init isn't used (it was to set them to non-blocking), but just in case we end up needing it should we almost make a file for scrapped code? Also, more importantly, the current printThis is not the printThis that does the job the original was supposed to--basically, since it looked like the printing formatting/stopping could be a problem, I switched it to a version that just prints or takes in input (it does NOT act like a poor-man's lock anymore), the old code did, but I'm not sure if it is functioning well --> should we just wait until locks are implemented and the program is neater before we delete it (or maybe a file for scrapped code as well) -- in the event that locks prove to be difficult to implement we might want to have that function so we at least have a starting place

**Comment by jorndorff** [comment]
Good points about printThis. I agree, let's take a crack at implementing locks and then decide what to do with that old code.

Regarding other commented code, I vote for just straight-up deleting it. The code is permanently in our commit history so we can always resurrect it from there. If you want to have a file of removed code locally, that's fine (the only person who decides your workflow is you :smile: ). But maybe list it in .gitignore?

**Comment by jorndorff** [comment]
I think this is ready to be closed after 8a27bb4177fa5102385426b3ccf7f27723e24aad

We can open more specific issues for other sections that need cleaned up in the future.
