### ISSUE TITLE
File Naming

### ISSUE THREAD

**Issue by mpavlak2018** [pingryiRT/ChatClient#20]
Can we get some input on what we think good names for the four files are? This should be fairly easy, we can just decide on something and close it.

**Comment by jorndorff** [comment]
My votes are for `Network` and `WorkerThread`.

To follow up on @mpavlak2018 's comment over in #10 , extend is still the right word in python (for once they share the same vocab!).

**Comment by jorndorff** [comment]
I've resolved this using the names I proposed above 40d059c6a6469a8ffcd0ddee194c3a1a0d3d9435 and 10f699195e8214fb066f1e5fbe4a3dd99abdec30. But if we decide on better ones, I'm all for it.
