### ISSUE TITLE
Make a shutdown methon in Network class

### ISSUE THREAD

**Issue by jorndorff** [pingryiRT/ChatClient#22]
I think all of this from the main program
```
# This should hopefully close a little nicer...
for peers in myNetwork.peerList:
	if peers.hasSock:
		peers.hasSock = False # Doing this before to try to prevent an error
		# peers.send() need to send something to initiate shutdown
		peers.Sock.shutdown(socket.SHUT_RDWR)
		peers.Sock.close()
```
should be moved into a shutdown method of some kind in the `Network` class. Then a client who uses our `Network` class (eg ourselves) doesn't need to be bothered by the nitty-gritty of sockets at the main program level.

Thoughts?

**Comment by mpavlak2018** [comment]
I think we should eventually, but I'm not sure that that method was ever fully implemented/not sure if it even works... I'm going to continue working on trying to allow more peers to join, but I think that after that is complete this could be a really good goal before we move on to try and create a better network structure, or if anyone wants to try to tackle it now?

**Comment by jorndorff** [comment]
I made this method in ef833c00bbaf112b85ec1adf3507b31dded2c8aa .

It isn't really tested though.
