### ISSUE TITLE
/exit Not working 

### ISSUE THREAD

**Issue by msun2019** [pingryiRT/ChatClient#3]
/exit does not work on my system but seems to work fine on Orndorff's computer

**Comment by jorndorff** [comment]
Can you confirm that this is still true in the most recent version?

Do we have a windows system we can test it on?

**Comment by jorndorff** [comment]
And actually, @mpavlak2018 , can you test this too?

**Comment by jorndorff** [comment]
Closed because the issue was no longer happening. Apparently one of the recent commits fixed it.

Let's make sure to always say *why* we're closing an issue.

**Comment by jorndorff** [comment]
Fixed this again in b8d8a9acc5598cd0dbb95034b2ab8a32e3aaacf8
