### ISSUE TITLE
Cannot reliably determine a system's LAN IP address

### ISSUE THREAD

**Issue by msun2019** [pingryiRT/ChatClient#4]
Line 14 is supposed to automatically get the user's IP address but it doesn't work for some reason.

**Comment by jorndorff** [comment]
Specifically, it doesn't work on @msun2019 's system. Tell us what OS (including version) and python interpreter (also including version) you're using.

**Comment by jorndorff** [comment]
I happen to know that this was a problem for @msun2019 on OSX, but not what version. The one-liner that I put into that function was taken from here: http://stackoverflow.com/questions/166506/

Seems like we'll probably have to actually dig in and get that working properly. Not sure how urgent it is, but definitely something to keep track of.

**Comment by jorndorff** [comment]
Oops, didn't mean to close it.

**Comment by jorndorff** [comment]
Michael and I made *some* progress on this. It is a little janky because it requires sending packets to google, and there are probably bugs we don't know about yet. But it at least kind of works on both OSX and Linux.

I vote to close for now and open a more specific issue if (when) we find it.

**Comment by jorndorff** [comment]
Lacking any feedback, I'm going to close this.

Please start participating in the issue queue.
