### ISSUE TITLE
Receiver crash when transmitter exited

### ISSUE THREAD

**Issue by mpavlak2018** [pingryiRT/ChatClient#5]
Traceback (most recent call last):
  File "chat-receiver.py", line 31, in <module>
    sock.shutdown(socket.SHUT_RDWR)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 57] Socket is not connected

**Comment by mpavlak2018** [comment]
Still happens when it is all local for me

**Comment by mpavlak2018** [comment]
I could very well be wrong on this, but I think it might be because we have a redundant shutdown on the receivers end (if you already have on the transmitter client.shutdown(socket.SHUT_RDWR), do you need  the sock.shutdown(socket.SHUT_RDWR) on the receiver's side--doesn't the transmitter already tell the receiver to shutdown?)

**Comment by jorndorff** [comment]
I think you're right. Removing the shutdown from the receiver code solves the crash on OSX (according to Mitchell) and does not create a crash on linux, so pending the results of testing the fix together, I think we are ready to commit that change.

**Comment by jorndorff** [comment]
Just to follow up. We agreed to Mitchell's solution, and removed the receiver's shutdown line.
